@StuffTracker.API_HostAddress = https://localhost:7115

###

POST {{StuffTracker.API_HostAddress}}/api/locations
Content-Type: application/json
{
  "Name": "Test home 27 march",
  "Description": "Test description 27 march"
}

###

GET {{StuffTracker.API_HostAddress}}/api/homes/a2134850-0c62-4848-b943-2c843f42e88e

###

GET {{StuffTracker.API_HostAddress}}/api/homes

###

POST {{StuffTracker.API_HostAddress}}/api/homes/locations
Content-Type: application/json

{
  "Name": "Storage 1",
  "Description": "Rooms test 27 march",
  "ParentId": "b261cfe0-1342-4972-b48f-3297c5c75888",
  "LocationType": "Storage"
}

###

GET {{StuffTracker.API_HostAddress}}/api/homes/a2134850-0c62-4848-b943-2c843f42e88e

###

GET {{StuffTracker.API_HostAddress}}/api/homes/a2134850-0c62-4848-b943-2c843f42e88e/locations

###
